spring.application.name=demo

# DB接続
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=postgres
spring.datasource.password=root

# SQL表示
spring.jpa.show-sql=true

# テーブル自動作成・更新
spring.jpa.hibernate.ddl-auto=update

# SQL見やすく表示
spring.jpa.properties.hibernate.format_sql=true

